"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { registerDid } from "@/app/actions/did-actions";

type Props = {
  userId: string;
};

export default function DidRegistrationForm({ userId }: Props) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  // Pre-popula o campo DID com o formato esperado para facilitar
  const [did, setDid] = useState(`did:web:vertex.unifesp.br:users:${userId}`);
  const [publicKey, setPublicKey] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  function handleSubmit() {
    setError(null);
    startTransition(async () => {
      const result = await registerDid(did, publicKey);
      if (result.success) {
        setSuccess(true);
        setTimeout(() => router.refresh(), 1500);
      } else {
        setError(result.error);
      }
    });
  }

  return (
    <div className="space-y-5">

      {error && (
        <div className="bg-red-950 border border-red-800 text-red-300 text-sm rounded-xl px-4 py-3">
          {error}
        </div>
      )}

      {success && (
        <div className="bg-emerald-950 border border-emerald-800 text-emerald-300 text-sm rounded-xl px-4 py-3">
          DID registered successfully!
        </div>
      )}

      <div>
        <label htmlFor="did" className="block text-sm font-medium text-gray-300 mb-2">
          Decentralized Identifier (DID)
        </label>
        <input
          id="did"
          type="text"
          value={did}
          onChange={(e) => setDid(e.target.value)}
          placeholder="did:web:example.com:users:abc123"
          className="w-full bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-xl px-4 py-3 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
        />
        <p className="text-xs text-gray-500 mt-1.5">
          Your unique decentralized identifier following the W3C DID specification.
        </p>
      </div>

      <div>
        <label htmlFor="publicKey" className="block text-sm font-medium text-gray-300 mb-2">
          Public Key (Multibase)
        </label>
        <input
          id="publicKey"
          type="text"
          value={publicKey}
          onChange={(e) => setPublicKey(e.target.value)}
          placeholder="z6MkpTHR8VNsBxYAAWHut2Geadd9jSwuBV8xRoAnwWsdvktH"
          className="w-full bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-xl px-4 py-3 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
        />
        <p className="text-xs text-gray-500 mt-1.5">
          Your Ed25519 public key in multibase format, generated by the Mobile Signer App.
        </p>
      </div>

      <button
        type="button"
        onClick={handleSubmit}
        disabled={isPending || success}
        className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-900 disabled:text-indigo-400 disabled:cursor-not-allowed text-white font-medium py-3 px-4 rounded-xl transition-colors cursor-pointer"
      >
        {isPending ? "Registering..." : "Register DID"}
      </button>

    </div>
  );
}